config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticated :user, -> user { user.email == 'nphaskins@gmail.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, skip: :registrations, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  post '/webhooks/process' => 'stripe#process_webhook'

  # Super Tenant
  constraints(:host => (Rails.env.production? ? 'styleguides.app' : 'lvh.me' ) ) do

    get 'register'      => 'register#index'
    post '/register'    => 'register#create'
    namespace :account do
      get '/'               => '/accounts#index'
      get '/collaborators' => 'collaborators#index'
      resources :invites
      resources :subscriptions do

        member do
          post 'update-card'    => 'subscriptions#update_card',   as: :update_card
          post 'cancel'         => 'subscriptions#cancel',        as: :cancel
          post 'reactivate'     => 'subscriptions#reactivate',    as: :reactivate
        end

      end
      resources :payments
      resources :brands do
        member do
          post '/connect-site'       => 'connect_site#connect',        as: :connect_site
          post '/connect-site-style' => 'connect_site#connect_style',  as: :connect_site_style
        end
      end
    end
  end

  # Tenant
  constraints(SubDomainConstraint) do
    get '/'   => 'brands#show', as: :brand_root

    resources :logos
    resources :colors
    resources :color_categories
    resources :fonts
    resources :spacers
    resources :components

    namespace :settings do
      get '/'         => '/settings#index'
      post '/update'  => '/settings#update', as: :update
    end

    namespace :invites do
      get '/'       => '/invites#index'
      post '/claim' => '/invites#claim'
    end
  end

  root 'home#index'

end

app/models/account.rb
class Account < ApplicationRecord

  belongs_to :owner, class_name:'User', optional: true
  has_many :brands, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_one :subscription, dependent: :destroy
  has_one :plan, class_name:'SubscriptionPlan', through: :subscription
  has_many :payments, class_name:'SubscriptionPayment', dependent: :nullify
  has_many :accounts_users, dependent: :destroy
	has_many :users, through: :accounts_users

  accepts_nested_attributes_for :owner, :subscription
  validates_associated :owner

  attr_accessor :newsletter, :terms

  def has_valid_subscription?
    subscription.present? && subscription.valid_subscription?
  end
end

app/models/accounts_user.rb
class AccountsUser < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :account
  has_many :colors, dependent: :destroy
  has_many :fonts, dependent: :destroy
  has_many :logos, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :color_categories, dependent: :destroy
  has_many :invites, dependent: :destroy

  validates_presence_of :name
  validates :subdomain,
    presence: true,
    uniqueness: { case_sensitive: false,
      message: '%{value} is already taken' },
    exclusion: { in: %w(www admin test app assets marketing blog cdn files support help),
      message: '%{value} is reserved' },
    format: { with: /\A[a-zA-Z0-9\-_]+\z/,
      message: 'must only contain letters, numbers, and may also include dash and underscore characters' }

  after_create_commit :setup_brand

  def primary_logo
    if logos.exists?
      logos.order(created_at: :asc).first
    end
  end

  private

    def setup_brand
      # @todo Trigger Cloudflare Job
      self.color_categories.create([{
        name:'Primaries'
      },{
        name:'Neutrals'
      },{
        name:'Supporting'
      }])
    end

end

app/models/color.rb
class Color < ApplicationRecord

  belongs_to :brand
  has_one :category, class_name:'ColorCategory'
  validates_presence_of :hex
  validate :hex_format, on: :create

  acts_as_tenant(:brand)

  private

    def hex_format
      unless hex =~ /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/i
        errors.add :hex, "Must be a valid hex color code"
      end
    end
end

app/models/color_category.rb
class ColorCategory < ApplicationRecord

  belongs_to :brand
  has_many :colors, dependent: :nullify

  acts_as_tenant(:brand)

  validates_presence_of :name
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :brand
  acts_as_tenant(:brand)
end

app/models/font.rb
class Font < ApplicationRecord

  belongs_to :brand

  acts_as_tenant(:brand)

  validates_presence_of :name, :size
end

app/models/image_uploader.rb
require 'image_processing/mini_magick'

class ImageUploader < Shrine

  def generate_location(io, context)
    type    = context[:record].class.name.downcase if context[:record]
    brand_id  = tenant_id(context[:record])
    tenant  = defined?(context[:record].brand_id) ? "tenant_#{brand_id}" : "tenant_0"
    name    = super # the default unique identifier

    [tenant, name].compact.join("/")
  end

  #plugin :processing # allows hooking into promoting
  #plugin :versions   # enable Shrine to handle a hash of files
  #plugin :delete_raw # delete processed files after uploading
  plugin :validation_helpers
  plugin :store_dimensions

  process(:store) do |io, context|
    versions = { original: io } # retain original

    io.download do |original|
      pipeline = ImageProcessing::MiniMagick.source(original)
      versions[:large]  = pipeline.resize_to_limit!(1280, nil)
      versions[:small]  = pipeline.resize_to_limit!(400, nil)
      versions[:thumb]  = pipeline.resize_to_fill!(150, 150, gravity: 'Center')
    end

    versions # return the hash of processed files
  end

  Attacher.validate do
    validate_max_size 5*1024*1024, message: "is too large (max is 5 MB)"
    validate_mime_type_inclusion %w[image/jpeg image/png]
    validate_extension_inclusion %w[jpg jpeg png]
  end

  private
    def tenant_id(record)
      if defined?(record.brand_id)
        record.brand_id
      elsif defined?(record.id)
        record.id
      else
        0
      end
    end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :account
  belongs_to :brand

  acts_as_tenant(:brand)

  before_create :generate_token

  validates_presence_of :email

  private
    def generate_token
      self.token    = Digest::SHA1.hexdigest([Time.now, rand].join)
    end
end

app/models/logo.rb
class Logo < ApplicationRecord
  belongs_to :brand

  include ImageUploader[:file]

  acts_as_tenant(:brand)

  validate :hex_format
  validates_presence_of :name, :file

  private

    def hex_format
      if display_color.present?
        unless display_color =~ /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/i
          errors.add :display_color, "Must be a valid hex color code"
        end
      end
    end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :plan, class_name:'SubscriptionPlan', foreign_key: 'subscription_plan_id'
  has_many :payments, class_name:'SubscriptionPayment', dependent: :nullify

  enum status: { trialing:0, pending:1, active: 2, past_due: 3, canceled:4, unpaid:5, free:6 }

  def valid_subscription?
    status == 'free' || (status == 'active' && !expired?)
  end

  def reactivateable?
    status == 'canceled' && !expired?
  end

  def cancelable?
    status == 'active'
  end

  def expired?
    expiration && (Time.current > expiration)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #validates_presence_of :email, :password
  has_one :account, foreign_key: :owner_id, dependent: :destroy
  #belongs_to :accounts_users, optional: true

end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  validates_uniqueness_of :webhook_id
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/views/partials/_brand_logo.html.erb
<%= link_to root_path, class:'brand-wrap' do %>
  <%= image_tag current_tenant.primary_logo.file_url(:small, public:true) %>
<% end %>

app/views/partials/_brand_nav.html.erb
<ul class="nav nav--material flex-column">
  <li class="nav-item"><%= link_to (octicon('dashboard', class:'nav-icon',height:24) + "Overview"), root_path, class:"#{'active' if 'brands' == controller_name} nav-link" %></li>
  <li class="nav-item"><%= link_to (octicon('star', class:'nav-icon',height:24) + "Logos"), logos_path, class:"#{'active' if 'logos' == controller_name} nav-link" %></li>
  <li class="nav-item"><%= link_to (octicon('paintcan', class:'nav-icon',height:24) + "Colors"), colors_path, class:"#{'active' if 'colors' == controller_name} nav-link" %></li>
  <li class="nav-item"><%= link_to (octicon('text-size', class:'nav-icon',height:24) + "Fonts"), fonts_path, class:"#{'active' if 'fonts' == controller_name} nav-link" %></li>
  <li class="nav-item"><%= link_to (octicon('archive', class:'nav-icon',height:24) + "Components"), components_path, class:"#{'active' if 'components' == controller_name} nav-link" %></li>
  <% if current_user_authorized_for_brand?  %>
    <li class="nav-item border-bottom my-4"></li>
    <li class="nav-item"><%= link_to (octicon('gear', class:'nav-icon',height:24) + "Settings"), settings_path, class:"#{'active' if 'settings' == controller_name} nav-link" %></li>
  <% end %>
</ul>

app/views/partials/_footer.html.erb
<footer class="app-footer mt-5">
  <div class="container font-size-16 color-neutral-6 pb-3">
    <p class="mb-0 border-top pt-3 d-block">© <%= Date.today.year %> Great Freakin Software Co. Built with <%= octicon('heart', style:'fill:#e74c3c;') %> in the mountains of Boone, NC.</p>
  </div>
</footer>

app/views/partials/_layout_header_favicons.html.erb
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="/favicon-128.png" sizes="128x128" />

app/views/partials/_notice.html.erb
<div id="notices">
  <% flash.each do |key, value| %>
    <div class="alert alert-snackbar bg-<%= key %> box-shadow-2">
      <p class="text-white mb-0"><%= value %></p>
    </div>
  <% end %>
</div>

app/views/partials/_stripe.html.erb
<script src="https://js.stripe.com/v3/"></script>
<script>
$(document).on('turbolinks:load', function(){

  var stripe = Stripe('<%= Rails.application.credentials[:stripe_test_publishable_key] %>');
  var elements = stripe.elements();
    // Custom styling can be passed to options when creating an Element.
  var style = {
    base: {
      // Add your base input styles here. For example:
      fontSize: '18px',
      color: '#486581',
      fontSmoothing: 'antialiased',
      '::placeholder': {
        color: '#627D98',
      }
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.

  if( !$('#card-element').length ) {
    return false;
  }
  card.mount('#card-element');

  var form = document.getElementById('form-payment');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    // ensure we're still submitting a payment and not an ach payment
    if( $(this).attr('id') == 'form-payment') {

      stripe.createToken(card).then(function(result) {
        if (result.error) {
          // Inform the customer that there was an error.
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
        } else {
          // Send the token to your server.
          stripeTokenHandler(result.token);
        }
      });

    } else {
      form.submit();
    }
  });

  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('form-payment');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }

})
</script>

app/views/partials/_stripe_fields.html.erb
<fieldset id="card-payment-fieldset" class="mb-3">
  <label>Payment</label>
  <div id="card-element"></div>
  <div id="card-errors" role="alert"></div>
</fieldset>