config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticated :user, -> user { user.email == 'nphaskins@gmail.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, skip: :registrations, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  post '/webhooks/process' => 'stripe#process_webhook'

  # Super Tenant
  constraints(:host => (Rails.env.production? ? 'styleguides.app' : 'lvh.me' ) ) do

    get 'register'      => 'register#index'
    post '/register'    => 'register#create'
    namespace :account do
      get '/'               => '/accounts#index'
      get '/collaborators' => 'collaborators#index'
      resources :invites
      resources :subscriptions do

        member do
          post 'update-card'    => 'subscriptions#update_card',   as: :update_card
          post 'cancel'         => 'subscriptions#cancel',        as: :cancel
          post 'reactivate'     => 'subscriptions#reactivate',    as: :reactivate
        end

      end
      resources :payments
      resources :brands do
        member do
          post '/connect-site'       => 'connect_site#connect',        as: :connect_site
          post '/connect-site-style' => 'connect_site#connect_style',  as: :connect_site_style
        end
      end
    end
  end

  # Tenant
  constraints(SubDomainConstraint) do
    get '/'   => 'brands#show', as: :brand_root

    resources :logos
    resources :colors
    resources :color_categories
    resources :fonts
    resources :spacers
    resources :components

    namespace :settings do
      get '/'         => '/settings#index'
      post '/update'  => '/settings#update', as: :update
    end

    namespace :invites do
      get '/'       => '/invites#index'
      post '/claim' => '/invites#claim'
    end
  end

  root 'home#index'

end

app/models/color_category.rb
class ColorCategory < ApplicationRecord

  belongs_to :brand
  has_many :colors, dependent: :nullify

  acts_as_tenant(:brand)

  validates_presence_of :name
end

app/controllers/color_categories_controller.rb
class ColorCategoriesController < ApplicationController
  layout 'brand'
  before_action :set_color_category, only: [:show, :edit, :update, :destroy]

  # GET /color_categories
  def index
    @color_categories = ColorCategory.all
  end

  # GET /color_categories/1
  def show
  end

  # GET /color_categories/new
  def new
    @color_category = ColorCategory.new
  end

  # GET /color_categories/1/edit
  def edit
  end

  # POST /color_categories
  def create
    @color_category = ColorCategory.new(color_category_params)

    if @color_category.save
      redirect_to color_categories_path, success: 'Color category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /color_categories/1
  def update
    if @color_category.update(color_category_params)
      redirect_to color_categories_path, success: 'Color category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /color_categories/1
  def destroy
    @color_category.destroy
    redirect_to color_categories_url, success: 'Color category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_category
      @color_category = ColorCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def color_category_params
      params.require(:color_category).permit(:name)
    end
end

app/helpers/color_categories_helper.rb
module ColorCategoriesHelper
end

app/views/color_categories/_form.html.erb
<%= simple_form_for(@color_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value:(@color_category.new_record? ? 'Add Category' : 'Update Category') %>
  </div>
<% end %>

app/views/color_categories/edit.html.erb
<h1>Editing Color Category</h1>

<%= render 'form', color_category: @color_category %>

<%= link_to 'Show', @color_category %> |
<%= link_to 'Back', color_categories_path %>

app/views/color_categories/index.html.erb
<header class="page-header row align-items-end">
  <div class="col-md-9">
    <h1 class="h3 mb-0"><%= link_to 'Colors', colors_path %> / Color Categories</h1>
  </div>
  <% if current_user_authorized_for_brand?  %>
    <div class="col-md-3 text-right">
      <%= link_to 'Add Category', new_color_category_path, class:'btn btn-sm btn-primary' %>
    </div>
  <% end %>
</header>

<% if @color_categories.exists? %>
  <div class="card">
    <div class="table-responsive">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @color_categories.each do |color_category| %>
            <tr>
              <td><%= color_category.name %></td>
              <td>
                <div class="dropdown ml-auto">
                  <a class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= octicon "kebab-vertical", height:20, class:'ml-1' %>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                    <%= link_to 'Edit', edit_color_category_path(color_category), class:'dropdown-item' %>
                    <%= link_to 'Delete', color_category, method: :delete, data:{confirm:'Are you sure?'}, class:'dropdown-item' %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="empty-state">
    <%= octicon('file', height:65) %>
    <div class="text-center lead">No categories have been created yet.</div>
  </div>
<% end %>

app/views/color_categories/new.html.erb
<header class="mb-4 row align-items-end">
  <div class="col-md-9">
    <h1 class="h3 mb-0"><%= link_to 'Colors', colors_path %> / <%= link_to 'Color Categories', color_categories_path %> / Add Color Category</h1>
  </div>
</header>

<%= render 'form', color_category: @color_category %>

app/views/color_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @color_category.brand %>
</p>

<p>
  <strong>Name:</strong>
  <%= @color_category.name %>
</p>

<%= link_to 'Edit', edit_color_category_path(@color_category) %> |
<%= link_to 'Back', color_categories_path %>