config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticated :user, -> user { user.email == 'nphaskins@gmail.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, skip: :registrations, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  post '/webhooks/process' => 'stripe#process_webhook'

  # Super Tenant
  constraints(:host => (Rails.env.production? ? 'styleguides.app' : 'lvh.me' ) ) do

    get 'register'      => 'register#index'
    post '/register'    => 'register#create'
    namespace :account do
      get '/'               => '/accounts#index'
      get '/collaborators' => 'collaborators#index'
      resources :invites
      resources :subscriptions do

        member do
          post 'update-card'    => 'subscriptions#update_card',   as: :update_card
          post 'cancel'         => 'subscriptions#cancel',        as: :cancel
          post 'reactivate'     => 'subscriptions#reactivate',    as: :reactivate
        end

      end
      resources :payments
      resources :brands do
        member do
          post '/connect-site'       => 'connect_site#connect',        as: :connect_site
          post '/connect-site-style' => 'connect_site#connect_style',  as: :connect_site_style
        end
      end
    end
  end

  # Tenant
  constraints(SubDomainConstraint) do
    get '/'   => 'brands#show', as: :brand_root

    resources :logos
    resources :colors
    resources :color_categories
    resources :fonts
    resources :spacers
    resources :components

    namespace :settings do
      get '/'         => '/settings#index'
      post '/update'  => '/settings#update', as: :update
    end

    namespace :invites do
      get '/'       => '/invites#index'
      post '/claim' => '/invites#claim'
    end
  end

  root 'home#index'

end

app/models/color.rb
class Color < ApplicationRecord

  belongs_to :brand
  has_one :category, class_name:'ColorCategory'
  validates_presence_of :hex
  validate :hex_format, on: :create

  acts_as_tenant(:brand)

  private

    def hex_format
      unless hex =~ /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/i
        errors.add :hex, "Must be a valid hex color code"
      end
    end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  layout 'brand'
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  def index
    @colors     = Color.all
    @categories = ColorCategory.includes(:colors).all
  end

  # GET /colors/1
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  def create
    @color = Color.new(color_params)

    if @color.save
      redirect_to colors_path, success: 'Color was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /colors/1
  def update
    if @color.update(color_params)
      redirect_to colors_path, success: 'Color was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /colors/1
  def destroy
    @color.destroy
    redirect_to colors_url, success: 'Color was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def color_params
      params.require(:color).permit(:hex, :color_category_id)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_color.html.erb
<li class="d-block">
  <div class="color card mb-1">
    <div class=" d-flex align-items-center ">
    <div class="swatch" style="background:<%= color.hex %>;"></div>
      <div class="card-body py-2 d-flex align-items-center">
        <ul class="list-inline">
          <li class="list-inline-item"><%= color.hex %></li>
        </ul>
        <% if current_user_authorized_for_brand? %>
          <div class="icon-dropdown ml-auto">
            <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= octicon "kebab-vertical", height:18%>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Edit', edit_color_path(color), class:'dropdown-item' %>
              <%= link_to 'Delete', color, method: :delete, data:{confirm:'Are you sure?'}, class:'dropdown-item' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/colors/_form.html.erb
<%= simple_form_for(@color) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :hex, required: true, input_html:{class:'colorpicker',value:(@color.hex.present? ? @color.hex : '#FFFFFF')}, hint:'Paste in, or select a color.' %>
    <%= f.input :color_category_id, collection:ColorCategory.all, include_blank: false, label:'Category', hint:'Choose a category for the color.' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/colors/_panel.html.erb
<div id="js--panel" class="js--panel-right">
  <div class="js--panel-inner">
    <button type="button" class="close panel-close" data-dismiss="panel" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="js--panel-content">Loading...</div>
  </div>
</div>

app/views/colors/edit.html.erb
<header class="mb-4 row align-items-end">
  <div class="col-md-9">
    <h1 class="h3 mb-0">Editing Color</h1>
  </div>
</header>

<%= render 'form', color: @color %>

app/views/colors/edit.js.erb
$('#js--panel .js--panel-content').html("<%= j render partial: 'colors/form', locals:{event:@event} %>");
$('#js--panel').addClass('show')
$('a[data-toggle="dropdown"]').dropdown('toggle')

app/views/colors/index.html.erb
<header class="page-header row align-items-end">
  <div class="col-md-6">
    <h1 class="h3 mb-0">Colors</h1>
  </div>
  <% if current_user_authorized_for_brand?  %>
    <div class="col-md-6 text-right">
      <%= link_to 'Manage Categories', color_categories_path, class:'btn btn-sm btn-outline-primary' %>
      <%= link_to 'Add Color', new_color_path, class:'btn btn-sm btn-primary' %>
    </div>
  <% end %>
</header>

<% if @categories.exists? %>

  <div class="row">
    <% @categories.each do |category| %>
      <div class="col-lg-4">
        <h2 class="h5 text-muted"><%= category.name %></h2>
        <ul class="list-unstyled color-list">
          <% category.colors.order(hex: :desc).each do |color| %>
            <%= render 'color', color: color %>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

<% elsif @colors.exists? %>
  <h2 class="h4">Neutrals</h2>
  <ul class="list-unstyled color-list row">
    <% @colors.each do |color| %>
      <%= render 'color', color: color %>
    <% end %>
  </ul>
<% else %>
  <div class="empty-state">
    <%= octicon('paintcan', height:65) %>
    <div class="text-center lead">You haven't created any colors yet.</div>
  </div>
<% end %>
<%= render 'panel' %>

app/views/colors/new.html.erb
<header class="mb-4 row align-items-end">
  <div class="col-md-9">
    <h1 class="h3 mb-0">Add Color</h1>
  </div>
</header>

<%= render 'form', color: @color %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @color.brand %>
</p>

<p>
  <strong>Hex:</strong>
  <%= @color.hex %>
</p>

<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>