config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticated :user, -> user { user.email == 'nphaskins@gmail.com' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, skip: :registrations, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  post '/webhooks/process' => 'stripe#process_webhook'

  # Super Tenant
  constraints(:host => (Rails.env.production? ? 'styleguides.app' : 'lvh.me' ) ) do

    get 'register'      => 'register#index'
    post '/register'    => 'register#create'
    namespace :account do
      get '/'               => '/accounts#index'
      get '/collaborators' => 'collaborators#index'
      resources :invites
      resources :subscriptions do

        member do
          post 'update-card'    => 'subscriptions#update_card',   as: :update_card
          post 'cancel'         => 'subscriptions#cancel',        as: :cancel
          post 'reactivate'     => 'subscriptions#reactivate',    as: :reactivate
        end

      end
      resources :payments
      resources :brands do
        member do
          post '/connect-site'       => 'connect_site#connect',        as: :connect_site
          post '/connect-site-style' => 'connect_site#connect_style',  as: :connect_site_style
        end
      end
    end
  end

  # Tenant
  constraints(SubDomainConstraint) do
    get '/'   => 'brands#show', as: :brand_root

    resources :logos
    resources :colors
    resources :color_categories
    resources :fonts
    resources :spacers
    resources :components

    namespace :settings do
      get '/'         => '/settings#index'
      post '/update'  => '/settings#update', as: :update
    end

    namespace :invites do
      get '/'       => '/invites#index'
      post '/claim' => '/invites#claim'
    end
  end

  root 'home#index'

end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :account
  has_many :colors, dependent: :destroy
  has_many :fonts, dependent: :destroy
  has_many :logos, dependent: :destroy
  has_many :components, dependent: :destroy
  has_many :color_categories, dependent: :destroy
  has_many :invites, dependent: :destroy

  validates_presence_of :name
  validates :subdomain,
    presence: true,
    uniqueness: { case_sensitive: false,
      message: '%{value} is already taken' },
    exclusion: { in: %w(www admin test app assets marketing blog cdn files support help),
      message: '%{value} is reserved' },
    format: { with: /\A[a-zA-Z0-9\-_]+\z/,
      message: 'must only contain letters, numbers, and may also include dash and underscore characters' }

  after_create_commit :setup_brand

  def primary_logo
    if logos.exists?
      logos.order(created_at: :asc).first
    end
  end

  private

    def setup_brand
      # @todo Trigger Cloudflare Job
      self.color_categories.create([{
        name:'Primaries'
      },{
        name:'Neutrals'
      },{
        name:'Supporting'
      }])
    end

end

app/controllers/account/brands_controller.rb
class Account::BrandsController < AccountsController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  def index
    @brands = @account.brands
  end

  # GET /brands/1
  def show
  end

  # GET /brands/new
  def new
    @brand = @account.brands.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = @account.brands.new(brand_params)

    if @brand.save
      redirect_to edit_account_brand_path(@brand), success: 'brand was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      redirect_to edit_account_brand_path(@brand), success: 'brand was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /brands/1
  def destroy
    @brand.destroy
    redirect_to brands_url, success: 'brand was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = @account.brands.where(id:params[:id])&.first
    end

    # Only allow a trusted parameter "white list" through.
    def brand_params
      params.require(:brand).permit(:name, :subdomain, :website)
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  layout 'brand'

  def show
    @brand = current_tenant
  end

end

app/helpers/account/brands_helper.rb
module Account::BrandsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/show.html.erb
<% if current_user_authorized_for_brand? %>

  <h3 class="h4 color-neutral-6 mb-1">Welcome to your style guide!</h3>
  <p class="w-50 color-neutral-6 font-size-16">We'll guide you through getting your logos uploaded, and colors in order before we set you on your way.</p>
  <ul class="list-unstyled list-steps">
    <li class="completed">
      <%= link_to 'Create brand', new_account_brand_path, class:'color-neutral-6' %>
    </li>
    <li>
      <%= link_to 'Add your logo', new_logo_path, class:'color-neutral-6' %>
    </li>
    <li>
      <%= link_to 'Add a component', new_component_path, class:'color-neutral-6' %>
    </li>
  </ul>

<% else %>
  <h1 class="h3 mb-4">Style Guide</h1>
  <div class="w-75">
    <p>As <%= current_tenant.name %> continues to grow, both as a product and a company, one challenge we are faced with is learning how to refine the <%= current_tenant.name %> brand identity and apply it cohesively to each of our products.</p>
    <p>We created this styleguide to act as a central location where we house a live inventory of UI components, brand guidelines, brand assets, code snippets, developer guidelines and more.</p>
    <p>Anyone working on the <%= current_tenant.name %> product is encouraged to stay familiar with this styleguide and help ensure that it is kept up-to-date.</p>
  </div>
<% end %>